### ISSUE TITLE
No module named triangular_diag

### ISSUE THREAD

**Issue by brianpenghe** [koszullab/E.coli.analysis#1]
Did you guys attach the triangular_diag module? It doesn't seem to be there

testrun$ python ../E_coli_analysis/python_codes/plot_mat_temp.py 
Traceback (most recent call last):
  File "../E_coli_analysis/python_codes/plot_mat_temp.py", line 8, in <module>
    import triangular_diag
ImportError: No module named triangular_diag

**Comment by axelcournac** [comment]
Hi,
I have just added the module triangular_diag.py to the python codes repository.
Best,
